CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --agreement_type toxicity 
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona woman --agreement_type toxicity 
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona man --agreement_type toxicity 
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona nonbinary --agreement_type toxicity 
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona transgender --agreement_type toxicity 
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona african\ american --agreement_type toxicity 
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona asian --agreement_type toxicity 
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona black --agreement_type toxicity 
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona hispanic --agreement_type toxicity 
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona indian --agreement_type toxicity 
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona pacific --agreement_type toxicity 
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona white --agreement_type toxicity 
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona bisexual --agreement_type toxicity 
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona pansexual --agreement_type toxicity 
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona asexual --agreement_type toxicity 
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona gay --agreement_type toxicity 
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona straight --agreement_type toxicity 
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona lower\ class --agreement_type toxicity 
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona middle\ class --agreement_type toxicity 
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona upper\ class --agreement_type toxicity 
# new generic
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona uneducated --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona primary\ school --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona middle\ school --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona high\ school --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona college --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona graduate --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona medical --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona scientific\ research --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona finance --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona consulting --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona technology --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona art --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona aerospace --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona railway --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona accounting --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona law --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona entertainment --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona management --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona sports --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona news --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona education --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona government --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona customer --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona sikhism --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona judaism --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona islam --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona hinduism --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona christianity --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona buddhism --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona atheism --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona socialism --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona populism --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona nationalism --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona liberalism --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona fascism --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona democracy --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona conservatism --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona communism --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona musculoskeletal\ disorders --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona special\ senses\ and\ speech --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona respiratory\ disorders --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona cardiovascular\ system\ disorders --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona digestive\ system\ disorders --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona genitourinary\ disorders --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona hematological\ disorders --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona skin\ disorders --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona endocrine\ disorders --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona congenital\ disorders --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona neurological\ disorders --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona mental\ disorders --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona cancer --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona immune\ system\ disorders --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona no\ disabilities --agreement_type toxicity  
# new specific
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona doctor --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona software\ developer --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona dentist --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona physician --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona orthodontist --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona statistician --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona surgeon --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona veterinarian --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona manager --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona nurse --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona mathematician --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona physical\ therapist --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona optometrist --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona anesthesiologist --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona psychologist --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona pilot --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona accountant --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona marketer --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona lawyer --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona plumber --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona chef --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona dancer --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona comedian --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona actor --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona model --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona writer --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona singer --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona poet --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona producer --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona composer --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona director --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona musician --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona engineer --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona ceo --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona consultant --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona financial\ analyst --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona partner --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona teacher --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona professor --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona trader --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona firefighter --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona linguist --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona social\ scientist --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona railway\ worker --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona driver --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona sewer --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona basketball\ player --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona boxer --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona reporter --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona waiter --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona alexander --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona victor --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona muhammad --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona kai --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona amit --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona gustavo --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona anastasia --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona isabelle --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona fatima --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona yumi --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona aparna --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona larissa --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona fidel\ castro --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona salvador\ allende --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona rosa\ luxemburg --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona clara\ zetkin --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona hugo\ chavez --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona jorg\ haider --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona eva\ peron --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona isabel\ peron --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona muammar\ gaddafi --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona francisco\ franco --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona golda\ meir --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona indira\ gandhi --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona john\ kennedy --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona willy\ brandt --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona benazir\ bhutto --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona corazon\ aquino --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona adolf\ hitler --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona benito\ mussolini --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona margherita\ sarfatti --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona maria\ primo --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona lyndon\ johnson --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona hubert\ humphrey --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona barbara\ jordan --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona shirley\ chisholm --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona mao\ zedong --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona ho\ chi\ minh --agreement_type toxicity  
CUDA_VISIBLE_DEVICES=2 python harmful_agreement.py --model_type alpaca --include_persona --persona jiang\ qing --agreement_type toxicity  