CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona woman --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona man --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona nonbinary --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona transgender --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona african\ american --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona asian --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona black --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona hispanic --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona indian --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona pacific --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona white --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona bisexual --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona pansexual --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona asexual --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona gay --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona straight --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona lower\ class --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona middle\ class --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona upper\ class --harm_type regard 
# new generic
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona uneducated --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona primary\ school --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona middle\ school --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona high\ school --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona college --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona graduate --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona medical --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona scientific\ research --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona finance --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona consulting --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona technology --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona art --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona aerospace --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona railway --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona accounting --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona law --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona entertainment --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona management --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona sports --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona news --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona education --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona government --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona customer --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona sikhism --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona judaism --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona islam --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona hinduism --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona christianity --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona buddhism --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona atheism --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona socialism --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona populism --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona nationalism --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona liberalism --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona fascism --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona democracy --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona conservatism --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona communism --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona musculoskeletal\ disorders --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona special\ senses\ and\ speech --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona respiratory\ disorders --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona cardiovascular\ system\ disorders --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona digestive\ system\ disorders --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona genitourinary\ disorders --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona hematological\ disorders --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona skin\ disorders --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona endocrine\ disorders --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona congenital\ disorders --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona neurological\ disorders --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona mental\ disorders --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona cancer --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona immune\ system\ disorders --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona no\ disabilities --harm_type regard 
# new specific
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona doctor --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona software\ developer --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona dentist --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona physician --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona orthodontist --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona statistician --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona surgeon --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona veterinarian --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona manager --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona nurse --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona mathematician --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona physical\ therapist --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona optometrist --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona anesthesiologist --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona psychologist --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona pilot --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona accountant --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona marketer --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona lawyer --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona plumber --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona chef --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona dancer --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona comedian --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona actor --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona model --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona writer --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona singer --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona poet --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona producer --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona composer --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona director --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona musician --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona engineer --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona ceo --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona consultant --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona financial\ analyst --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona partner --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona teacher --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona professor --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona trader --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona firefighter --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona linguist --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona social\ scientist --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona railway\ worker --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona driver --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona sewer --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona basketball\ player --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona boxer --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona reporter --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona waiter --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona alexander --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona victor --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona muhammad --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona kai --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona amit --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona gustavo --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona anastasia --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona isabelle --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona fatima --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona yumi --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona aparna --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona larissa --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona fidel\ castro --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona salvador\ allende --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona rosa\ luxemburg --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona clara\ zetkin --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona hugo\ chavez --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona jorg\ haider --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona eva\ peron --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona isabel\ peron --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona muammar\ gaddafi --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona francisco\ franco --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona golda\ meir --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona indira\ gandhi --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona john\ kennedy --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona willy\ brandt --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona benazir\ bhutto --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona corazon\ aquino --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona adolf\ hitler --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona benito\ mussolini --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona margherita\ sarfatti --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona maria\ primo --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona lyndon\ johnson --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona hubert\ humphrey --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona barbara\ jordan --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona shirley\ chisholm --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona mao\ zedong --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona ho\ chi\ minh --harm_type regard 
CUDA_VISIBLE_DEVICES=6 python offensiveness.py --model_type chatgpt --generator rtp --include_persona --persona jiang\ qing --harm_type regard 